fix C23 compilation
With GCC 15 defaulting to C23, mrfioc2 fails to build with:

    ../devWfMailbox.c:91:5: error: initialization of 'long int (*)(void)' from incompatible pointer type 'long int (*)(waveformRecord *)' [-Wincompatible-pointer-types]

This is because [`DEVSUPFUN`] is defined as `long (*)()` which in C23
is equivalent to `long (*)(void)` instead of unspecified arguments.

This patch fixes it by explicitly casting to `DEVSUPFUN`,
which is technically not correct since the `DEVSUPFUN` definition isn't,
but has been done in other EPICS support modules and should work.

  [`DEVSUPFUN`]: https://github.com/epics-base/epics-base/blob/33f4d15ff340d4af428d2b111e9d84bbaadf5087/modules/database/src/ioc/dbStatic/devSup.h#L139